server:
  port: 8103
spring:
  application:
    name: boa-saude-consults-api
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  data:
    mongodb:
      uri: mongodb://localhost:27017/boa_saude
feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000
        loggerLevel: basic
    implementations:
      coverages: boa-saude-coverages-api
      specialties: boa-saude-specialties-api
      people: boa-saude-people-api
      policies: boa-saude-policies-api
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
