server:
  port: 8102
spring:
  application:
    name: boa-saude-policies-api
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  data:
    mongodb:
      uri: mongodb://localhost:27017/boa_saude
feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000
        loggerLevel: basic
    implementations:
      insurances: boa-saude-insurances-api
      people: boa-saude-people-api
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
